CrudStudent/Models/Product.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CrudProduct.Models
{
    public class Product
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(20)]
        public string Group { get; set; }
        [Required]
        [StringLength(20)]
        public string RollNumber { get; set; }

        [Required]
        [StringLength(20)]
        public string Name { get; set; }

        [StringLength(300)]
        public string Comment { get; set; }
        [Required]
        [StringLength(20)]
        public string Category { get; set; }
        [Required]
        [StringLength(500)]
        public string ImageUrl { get; set; }
        [Required(ErrorMessage = "Please choose Front image")]
        [Display(Name = "Front Image")]
        [NotMapped]
        public IFormFile FrontImage { get; set; }
        public string BackImageUrl { get; set; }
        [Display(Name = "Back Image")]
        [NotMapped]
        public IFormFile BackImage { get; set; }
    }
}

CrudStudent/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CrudProduct.Models;
using CrudStudent.Data;

namespace CrudStudent.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IHostEnvironment _hostEnvironment;
        private readonly CrudStudentContext _context;

        public ProductsController(CrudStudentContext context, IHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            //return _context.Product != null ? 
            //            View(await _context.Product.ToListAsync()) :
            //            Problem("Entity set 'CrudStudentContext.Product'  is null.");

            List<Product> products = _context.Product.ToList();
            return View(products);
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            ViewBag.Category = GetCategories();
            Product product = new Product();
            return View(product);
        }
        private List<SelectListItem> GetCategories()
        {
            var lstCategories = _context.Categories.Select(ct => new SelectListItem()
            {
                Value = ct.CtCode.ToString(),
                Text = ct.CatName
            }).ToList();

            lstCategories.Insert(0, new SelectListItem
            {
                Value = null,
                Text = "-----Select category-----"
            });

            return lstCategories;
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product product)
        {
            string uniqueFileName = UploadedFile(product);
            string backFileName = GetBackImageFile(product);

            product.BackImageUrl = backFileName;
            product.ImageUrl = uniqueFileName;
            _context.Attach(product);
            _context.Entry(product).State = EntityState.Added;
            _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private string UploadedFile(Product product)
        {
            string uniqueFileName = null;
            if (product.FrontImage != null)
            {
                string uploadsFolder = Path.Combine(_hostEnvironment.ContentRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + product.FrontImage.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    product.FrontImage.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }
        private string GetBackImageFile(Product product)
        {
            string uniqueFileName = null;
            if (product.BackImage != null)
            {
                string uploadsFolder = Path.Combine(_hostEnvironment.ContentRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + product.BackImage.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    product.BackImage.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }
        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Group,RollNumber,Name,Comment,Category,ImageUrl")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Product == null)
            {
                return Problem("Entity set 'CrudStudentContext.Product'  is null.");
            }
            var product = await _context.Product.FindAsync(id);
            if (product != null)
            {
                _context.Product.Remove(product);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
          return (_context.Product?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

CrudStudent/Views/Shared/Components/ImageUploader/ImageUploaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace CrudStudent.Views.Shared.Components.ImageUploader
{
    public class ImageUploaderViewComponent : ViewComponent
    {
       public ImageUploaderViewComponent()
        {

        }
        public IViewComponentResult Invoke(string FileName)
        {
            return View("Default", FileName);
        }
    }
}

CrudStudent/Views/Products/Create.cshtml
@model CrudProduct.Models.Product

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Group" class="control-label"></label>
                <input asp-for="Group" class="form-control" />
                <span asp-validation-for="Group" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RollNumber" class="control-label"></label>
                <input asp-for="RollNumber" class="form-control" />
                <span asp-validation-for="RollNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comment" class="control-label"></label>
                <input asp-for="Comment" class="form-control" />
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <select asp-for="Category" class="form-control" asp-items="ViewBag.Category"></select>
            </div>
            <div class="col-md-6">
                <vc:image-uploader file-name="@nameof(Model.FrontImage)"> </vc:image-uploader>
            </div>
            <div class="col-md-6">
                <vc:image-uploader file-name="@nameof(Model.BackImage)"> </vc:image-uploader>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />

            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script>
    $(".custome-file-input").on("change", function () {
        var fileName = $(this).val().split("\\").pop();
        $(this).siblings(".custome-file-input").addClass("selected").html(fileName)
    });
</script>

CrudStudent/Views/Products/Delete.cshtml
@model CrudProduct.Models.Product

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Group)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Group)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RollNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RollNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CrudStudent/Views/Products/Details.cshtml
@model CrudProduct.Models.Product

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Group)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Group)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RollNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RollNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CrudStudent/Views/Products/Edit.cshtml
@model CrudProduct.Models.Product

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Group" class="control-label"></label>
                <input asp-for="Group" class="form-control" />
                <span asp-validation-for="Group" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RollNumber" class="control-label"></label>
                <input asp-for="RollNumber" class="form-control" />
                <span asp-validation-for="RollNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comment" class="control-label"></label>
                <input asp-for="Comment" class="form-control" />
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CrudStudent/Views/Products/Index.cshtml
@model IEnumerable<CrudProduct.Models.Product>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th></th>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.Group)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RollNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comment)
            </th>
          
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                    <img src="~/Image/@item.ImageUrl" width="150" height="150" />
            </td>
                <td>
                    <img src="~/Image/@item.BackImageUrl" width="150" height="150" />
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Group)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RollNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comment)
            </td>
            <div>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-info">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-primary ml-1">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger ml-1">Delete</a>
            </div>
        </tr>
}
    </tbody>
</table>